language: java
jdk: openjdk12
os: linux
dist: trusty
script: 
  - ./gradlew check
  - ./gradlew sonarqube
  - ./gradlew downloadCloudSdk
  - gcloud auth activate-service-account  --key-file=serviceaccount.json
  - ./gradlew appengineDeploy
 