language: java
jdk: openjdk12
os: linux
dist: trusty
script: 
  - ./gradlew check
  - ./gradlew sonarqube
  - ./gradlew buildDockerImage

deploy:
  provider: gae
  keyfile: serviceaccount.json
  project: My Project 86483