language: java
jdk: openjdk12
os: linux
dist: trusty
sudo: required
services:
  - docker
script: 
  - ./gradlew check
  - ./gradlew sonarqube
  - ./gradlew downloadCloudSdk
  - gcloud auth activate-service-account  --key-file=serviceaccount.json
  - gcloud app versions start --service default 1
  - ./gradlew appengineDeploy
  - gcloud app versions stop --service default 1